# Generated by Django 5.0.6 on 2024-06-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba_cantidad_alter_prueba_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
