# Generated by Django 5.0.6 on 2024-06-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_empleado_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilidades',
            new_name='habilidad',
        ),
    ]
