# Generated by Django 5.0.6 on 2024-06-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='habilidades',
            new_name='habilidad',
        ),
    ]
