# Generated by Django 5.0.6 on 2024-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_empleado_options_empleado_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=120, verbose_name='Nombre Completo'),
        ),
    ]
