# Generated by Django 5.0.6 on 2024-06-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_alter_empleado_avatar_alter_empleado_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(default=True, upload_to='empleados', verbose_name='Imagen'),
        ),
    ]
